import { PlayInGameDefinition, ResultsState, SeriesDefinition, SlotRef, Team, TeamId } from "./types";

const nbaLogoUrl = (nbaTeamId: number) =>
  `https://cdn.nba.com/logos/nba/${nbaTeamId}/global/L/logo.svg`;

const slotTeam = (teamId: TeamId, seed?: number): SlotRef => ({
  type: "team",
  teamId,
  seed,
});

export const PLAYOFF_SEASON_LABEL = "2025-26 NBA Postseason";
export const DEFAULT_POOL_LOCK_AT = "2026-04-14T16:00:00-07:00";
export const DEFAULT_TIEBREAKER_QUESTION =
  "Tiebreaker: combined points scored in the championship-clinching NBA Finals game.";

export const SCORING_RULES = {
  playInWinner: 2,
  seriesByRound: {
    "round-1": {
      winner: 5,
      exactLength: 2,
    },
    semifinals: {
      winner: 10,
      exactLength: 3,
    },
    "conference-finals": {
      winner: 20,
      exactLength: 5,
    },
    finals: {
      winner: 40,
      exactLength: 10,
    },
  },
} as const;

export const teams: Team[] = [
  {
    id: "det",
    nbaTeamId: 1610612765,
    tricode: "DET",
    city: "Detroit",
    name: "Pistons",
    shortName: "Pistons",
    displayName: "Detroit Pistons",
    conference: "East",
    defaultSeed: 1,
    logo: nbaLogoUrl(1610612765),
    colors: { primary: "#1D428A", secondary: "#C8102E", accent: "#BEC0C2" },
  },
  {
    id: "bos",
    nbaTeamId: 1610612738,
    tricode: "BOS",
    city: "Boston",
    name: "Celtics",
    shortName: "Celtics",
    displayName: "Boston Celtics",
    conference: "East",
    defaultSeed: 2,
    logo: nbaLogoUrl(1610612738),
    colors: { primary: "#007A33", secondary: "#BA9653", accent: "#FFFFFF" },
  },
  {
    id: "nyk",
    nbaTeamId: 1610612752,
    tricode: "NYK",
    city: "New York",
    name: "Knicks",
    shortName: "Knicks",
    displayName: "New York Knicks",
    conference: "East",
    defaultSeed: 3,
    logo: nbaLogoUrl(1610612752),
    colors: { primary: "#006BB6", secondary: "#F58426", accent: "#BEC0C2" },
  },
  {
    id: "cle",
    nbaTeamId: 1610612739,
    tricode: "CLE",
    city: "Cleveland",
    name: "Cavaliers",
    shortName: "Cavaliers",
    displayName: "Cleveland Cavaliers",
    conference: "East",
    defaultSeed: 4,
    logo: nbaLogoUrl(1610612739),
    colors: { primary: "#860038", secondary: "#FDBB30", accent: "#041E42" },
  },
  {
    id: "tor",
    nbaTeamId: 1610612761,
    tricode: "TOR",
    city: "Toronto",
    name: "Raptors",
    shortName: "Raptors",
    displayName: "Toronto Raptors",
    conference: "East",
    defaultSeed: 5,
    logo: nbaLogoUrl(1610612761),
    colors: { primary: "#CE1141", secondary: "#000000", accent: "#A1A1A4" },
  },
  {
    id: "atl",
    nbaTeamId: 1610612737,
    tricode: "ATL",
    city: "Atlanta",
    name: "Hawks",
    shortName: "Hawks",
    displayName: "Atlanta Hawks",
    conference: "East",
    defaultSeed: 6,
    logo: nbaLogoUrl(1610612737),
    colors: { primary: "#E03A3E", secondary: "#C1D32F", accent: "#26282A" },
  },
  {
    id: "phi",
    nbaTeamId: 1610612755,
    tricode: "PHI",
    city: "Philadelphia",
    name: "76ers",
    shortName: "76ers",
    displayName: "Philadelphia 76ers",
    conference: "East",
    defaultSeed: 7,
    logo: nbaLogoUrl(1610612755),
    colors: { primary: "#006BB6", secondary: "#ED174C", accent: "#FFFFFF" },
  },
  {
    id: "orl",
    nbaTeamId: 1610612753,
    tricode: "ORL",
    city: "Orlando",
    name: "Magic",
    shortName: "Magic",
    displayName: "Orlando Magic",
    conference: "East",
    defaultSeed: 8,
    logo: nbaLogoUrl(1610612753),
    colors: { primary: "#0077C0", secondary: "#C4CED4", accent: "#000000" },
  },
  {
    id: "cha",
    nbaTeamId: 1610612766,
    tricode: "CHA",
    city: "Charlotte",
    name: "Hornets",
    shortName: "Hornets",
    displayName: "Charlotte Hornets",
    conference: "East",
    defaultSeed: 9,
    logo: nbaLogoUrl(1610612766),
    colors: { primary: "#1D1160", secondary: "#00788C", accent: "#A1A1A4" },
  },
  {
    id: "mia",
    nbaTeamId: 1610612748,
    tricode: "MIA",
    city: "Miami",
    name: "Heat",
    shortName: "Heat",
    displayName: "Miami Heat",
    conference: "East",
    defaultSeed: 10,
    logo: nbaLogoUrl(1610612748),
    colors: { primary: "#98002E", secondary: "#F9A01B", accent: "#000000" },
  },
  {
    id: "okc",
    nbaTeamId: 1610612760,
    tricode: "OKC",
    city: "Oklahoma City",
    name: "Thunder",
    shortName: "Thunder",
    displayName: "Oklahoma City Thunder",
    conference: "West",
    defaultSeed: 1,
    logo: nbaLogoUrl(1610612760),
    colors: { primary: "#007AC1", secondary: "#EF3B24", accent: "#FDBB30" },
  },
  {
    id: "sas",
    nbaTeamId: 1610612759,
    tricode: "SAS",
    city: "San Antonio",
    name: "Spurs",
    shortName: "Spurs",
    displayName: "San Antonio Spurs",
    conference: "West",
    defaultSeed: 2,
    logo: nbaLogoUrl(1610612759),
    colors: { primary: "#000000", secondary: "#C4CED4", accent: "#FFFFFF" },
  },
  {
    id: "den",
    nbaTeamId: 1610612743,
    tricode: "DEN",
    city: "Denver",
    name: "Nuggets",
    shortName: "Nuggets",
    displayName: "Denver Nuggets",
    conference: "West",
    defaultSeed: 3,
    logo: nbaLogoUrl(1610612743),
    colors: { primary: "#0E2240", secondary: "#FEC524", accent: "#8B2131" },
  },
  {
    id: "lal",
    nbaTeamId: 1610612747,
    tricode: "LAL",
    city: "Los Angeles",
    name: "Lakers",
    shortName: "Lakers",
    displayName: "Los Angeles Lakers",
    conference: "West",
    defaultSeed: 4,
    logo: nbaLogoUrl(1610612747),
    colors: { primary: "#552583", secondary: "#FDB927", accent: "#FFFFFF" },
  },
  {
    id: "hou",
    nbaTeamId: 1610612745,
    tricode: "HOU",
    city: "Houston",
    name: "Rockets",
    shortName: "Rockets",
    displayName: "Houston Rockets",
    conference: "West",
    defaultSeed: 5,
    logo: nbaLogoUrl(1610612745),
    colors: { primary: "#CE1141", secondary: "#000000", accent: "#C4CED4" },
  },
  {
    id: "min",
    nbaTeamId: 1610612750,
    tricode: "MIN",
    city: "Minnesota",
    name: "Timberwolves",
    shortName: "Wolves",
    displayName: "Minnesota Timberwolves",
    conference: "West",
    defaultSeed: 6,
    logo: nbaLogoUrl(1610612750),
    colors: { primary: "#0C2340", secondary: "#236192", accent: "#9EA2A2" },
  },
  {
    id: "phx",
    nbaTeamId: 1610612756,
    tricode: "PHX",
    city: "Phoenix",
    name: "Suns",
    shortName: "Suns",
    displayName: "Phoenix Suns",
    conference: "West",
    defaultSeed: 7,
    logo: nbaLogoUrl(1610612756),
    colors: { primary: "#1D1160", secondary: "#E56020", accent: "#63727A" },
  },
  {
    id: "por",
    nbaTeamId: 1610612757,
    tricode: "POR",
    city: "Portland",
    name: "Trail Blazers",
    shortName: "Blazers",
    displayName: "Portland Trail Blazers",
    conference: "West",
    defaultSeed: 8,
    logo: nbaLogoUrl(1610612757),
    colors: { primary: "#E03A3E", secondary: "#000000", accent: "#B6BFBF" },
  },
  {
    id: "lac",
    nbaTeamId: 1610612746,
    tricode: "LAC",
    city: "LA",
    name: "Clippers",
    shortName: "Clippers",
    displayName: "LA Clippers",
    conference: "West",
    defaultSeed: 9,
    logo: nbaLogoUrl(1610612746),
    colors: { primary: "#C8102E", secondary: "#1D428A", accent: "#BEC0C2" },
  },
  {
    id: "gsw",
    nbaTeamId: 1610612744,
    tricode: "GSW",
    city: "Golden State",
    name: "Warriors",
    shortName: "Warriors",
    displayName: "Golden State Warriors",
    conference: "West",
    defaultSeed: 10,
    logo: nbaLogoUrl(1610612744),
    colors: { primary: "#1D428A", secondary: "#FFC72C", accent: "#BEC0C2" },
  },
];

export const teamsById = Object.fromEntries(
  teams.map((team) => [team.id, team]),
) as Record<TeamId, Team>;

export const seededTeamIds = new Set(teams.map((team) => team.id));

export const playInGames: PlayInGameDefinition[] = [
  {
    id: "east-playin-78",
    conference: "East",
    round: "play-in",
    label: "East 7 vs 8",
    seedOutcome: 7,
    note: "Winner becomes the East No. 7 seed",
    homeSlot: slotTeam("phi", 7),
    awaySlot: slotTeam("orl", 8),
  },
  {
    id: "east-playin-910",
    conference: "East",
    round: "play-in",
    label: "East 9 vs 10",
    note: "Loser is eliminated",
    homeSlot: slotTeam("cha", 9),
    awaySlot: slotTeam("mia", 10),
  },
  {
    id: "east-playin-8",
    conference: "East",
    round: "play-in",
    label: "East 8-Seed Game",
    seedOutcome: 8,
    note: "Winner becomes the East No. 8 seed",
    homeSlot: { type: "play-in-loser", gameId: "east-playin-78" },
    awaySlot: { type: "play-in-winner", gameId: "east-playin-910" },
  },
  {
    id: "west-playin-78",
    conference: "West",
    round: "play-in",
    label: "West 7 vs 8",
    seedOutcome: 7,
    note: "Winner becomes the West No. 7 seed",
    homeSlot: slotTeam("phx", 7),
    awaySlot: slotTeam("por", 8),
  },
  {
    id: "west-playin-910",
    conference: "West",
    round: "play-in",
    label: "West 9 vs 10",
    note: "Loser is eliminated",
    homeSlot: slotTeam("lac", 9),
    awaySlot: slotTeam("gsw", 10),
  },
  {
    id: "west-playin-8",
    conference: "West",
    round: "play-in",
    label: "West 8-Seed Game",
    seedOutcome: 8,
    note: "Winner becomes the West No. 8 seed",
    homeSlot: { type: "play-in-loser", gameId: "west-playin-78" },
    awaySlot: { type: "play-in-winner", gameId: "west-playin-910" },
  },
];

export const playInById = Object.fromEntries(
  playInGames.map((game) => [game.id, game]),
) as Record<string, PlayInGameDefinition>;

export const seriesDefinitions: SeriesDefinition[] = [
  {
    id: "east-r1-1",
    conference: "East",
    round: "round-1",
    label: "East Round 1 · 1 vs 8",
    note: "Detroit vs East No. 8 seed",
    homeSlot: slotTeam("det", 1),
    awaySlot: { type: "play-in-winner", gameId: "east-playin-8" },
  },
  {
    id: "east-r1-2",
    conference: "East",
    round: "round-1",
    label: "East Round 1 · 2 vs 7",
    note: "Boston vs East No. 7 seed",
    homeSlot: slotTeam("bos", 2),
    awaySlot: { type: "play-in-winner", gameId: "east-playin-78" },
  },
  {
    id: "east-r1-3",
    conference: "East",
    round: "round-1",
    label: "East Round 1 · 3 vs 6",
    note: "New York vs Atlanta",
    homeSlot: slotTeam("nyk", 3),
    awaySlot: slotTeam("atl", 6),
  },
  {
    id: "east-r1-4",
    conference: "East",
    round: "round-1",
    label: "East Round 1 · 4 vs 5",
    note: "Cleveland vs Toronto",
    homeSlot: slotTeam("cle", 4),
    awaySlot: slotTeam("tor", 5),
  },
  {
    id: "west-r1-1",
    conference: "West",
    round: "round-1",
    label: "West Round 1 · 1 vs 8",
    note: "Oklahoma City vs West No. 8 seed",
    homeSlot: slotTeam("okc", 1),
    awaySlot: { type: "play-in-winner", gameId: "west-playin-8" },
  },
  {
    id: "west-r1-2",
    conference: "West",
    round: "round-1",
    label: "West Round 1 · 2 vs 7",
    note: "San Antonio vs West No. 7 seed",
    homeSlot: slotTeam("sas", 2),
    awaySlot: { type: "play-in-winner", gameId: "west-playin-78" },
  },
  {
    id: "west-r1-3",
    conference: "West",
    round: "round-1",
    label: "West Round 1 · 3 vs 6",
    note: "Denver vs Minnesota",
    homeSlot: slotTeam("den", 3),
    awaySlot: slotTeam("min", 6),
  },
  {
    id: "west-r1-4",
    conference: "West",
    round: "round-1",
    label: "West Round 1 · 4 vs 5",
    note: "Lakers vs Houston",
    homeSlot: slotTeam("lal", 4),
    awaySlot: slotTeam("hou", 5),
  },
  {
    id: "east-sf-1",
    conference: "East",
    round: "semifinals",
    label: "East Semifinal · Top Half",
    note: "Winner of 1/8 vs winner of 4/5",
    homeSlot: { type: "series-winner", seriesId: "east-r1-1" },
    awaySlot: { type: "series-winner", seriesId: "east-r1-4" },
  },
  {
    id: "east-sf-2",
    conference: "East",
    round: "semifinals",
    label: "East Semifinal · Bottom Half",
    note: "Winner of 2/7 vs winner of 3/6",
    homeSlot: { type: "series-winner", seriesId: "east-r1-2" },
    awaySlot: { type: "series-winner", seriesId: "east-r1-3" },
  },
  {
    id: "west-sf-1",
    conference: "West",
    round: "semifinals",
    label: "West Semifinal · Bottom Half",
    note: "Winner of 1/8 vs winner of 4/5",
    homeSlot: { type: "series-winner", seriesId: "west-r1-1" },
    awaySlot: { type: "series-winner", seriesId: "west-r1-4" },
  },
  {
    id: "west-sf-2",
    conference: "West",
    round: "semifinals",
    label: "West Semifinal · Top Half",
    note: "Winner of 2/7 vs winner of 3/6",
    homeSlot: { type: "series-winner", seriesId: "west-r1-2" },
    awaySlot: { type: "series-winner", seriesId: "west-r1-3" },
  },
  {
    id: "east-cf",
    conference: "East",
    round: "conference-finals",
    label: "Eastern Conference Finals",
    note: "Winner reaches the NBA Finals",
    homeSlot: { type: "series-winner", seriesId: "east-sf-1" },
    awaySlot: { type: "series-winner", seriesId: "east-sf-2" },
  },
  {
    id: "west-cf",
    conference: "West",
    round: "conference-finals",
    label: "Western Conference Finals",
    note: "Winner reaches the NBA Finals",
    homeSlot: { type: "series-winner", seriesId: "west-sf-1" },
    awaySlot: { type: "series-winner", seriesId: "west-sf-2" },
  },
  {
    id: "nba-finals",
    conference: "NBA",
    round: "finals",
    label: "NBA Finals",
    note: "First to four wins the championship",
    homeSlot: { type: "series-winner", seriesId: "east-cf" },
    awaySlot: { type: "series-winner", seriesId: "west-cf" },
  },
];

export const seriesById = Object.fromEntries(
  seriesDefinitions.map((series) => [series.id, series]),
) as Record<string, SeriesDefinition>;

export const BRACKET_LAYOUT = {
  East: {
    playIn: ["east-playin-8", "east-playin-910", "east-playin-78"],
    round1: ["east-r1-1", "east-r1-4", "east-r1-3", "east-r1-2"],
    semifinals: ["east-sf-1", "east-sf-2"],
    conferenceFinals: ["east-cf"],
  },
  West: {
    playIn: ["west-playin-78", "west-playin-910", "west-playin-8"],
    round1: ["west-r1-2", "west-r1-3", "west-r1-4", "west-r1-1"],
    semifinals: ["west-sf-2", "west-sf-1"],
    conferenceFinals: ["west-cf"],
  },
} as const;

export const TOTAL_PICKABLE_MATCHUPS =
  playInGames.length + seriesDefinitions.length;

export const createSeededResultsState = (): ResultsState => ({
  playIn: Object.fromEntries(
    playInGames.map((game) => [
      game.id,
      {
        matchupId: game.id,
        status: "scheduled",
        games: [],
      },
    ]),
  ),
  series: Object.fromEntries(
    seriesDefinitions.map((series) => [
      series.id,
      {
        matchupId: series.id,
        status: "scheduled",
        wins: {},
        games: [],
      },
    ]),
  ),
  lastUpdated: undefined,
  liveSyncNote: "No live postseason results have been synced yet.",
});
